### ISSUE TITLE
Getting People Onboard

### ISSUE THREAD

**Issue by Saishreekouda** [opencodeiiita/DonateASmile#30]
**OPEN TO ALL. NO NEED TO CLAIM. NO SUBMISSION WILL BE ACCEPTED AFTER 27TH DEC 12 MIDNIGHT.**

Your next task in this DonateASmile App Design Repo is to design the onboarding screens for the DonateASmile app. Do check out this tutorial to know about what is onboarding within app design [https://www.youtube.com/watch?v=goPCYWvpnUI](https://www.youtube.com/watch?v=goPCYWvpnUI)

## Submission Guideline:

- Design onboarding screens (Minimum 3) for DonateASmile app based on your understanding of the app from the given user flow : [https://www.figma.com/file/Ex3YtTGzRVO5rgiU8NZcj0/DONATEASMILE?node-id=0%3A1&t=zgB6wPWFL5LaYRBZ-0](https://www.figma.com/file/Ex3YtTGzRVO5rgiU8NZcj0/DONATEASMILE?node-id=0%3A1&t=zgB6wPWFL5LaYRBZ-0)
( Special thanks to @BINGABABA  for contributing this great user flow in the first task)
- The onboarding screens must contain a login/sign up screen. The remaining screens' content is completely up to you.
- Submit the Figma file link in a .txt folder and submit the file in **UI Task - 1** folder ONLY.

## Minimum Design Criteria (MDC)

 Since it is a 40 point task, do read and fulfil the MDC accordingly.

- There should be a login/Sign up screen along with minimum 2 other screens.
- The onboarding screens must look like onboarding screens and not like any other screens of the app.
- If you plan to use illustrations and images, they should match in colour and have a consistent theme across all of the screens.
- The written content on the screens should be short but convincing. If not done correctly, it is the onboarding screens that cause the drop-off rates in apps.
- Along with convincing the user that the app is worthwhile of their time, it should also clarify fundamental purpose of the app.

If some of these things appear complex to you, don't worry too much 😅. Since creating onboarding screens is a form of art in and of itself, beginners may find the process intimidating. You can ping us on discord in the DonateASmile channel and we will be happy to help you with your queries.

**Comment by hargunkaur286** [comment]
claim
