### ISSUE TITLE
Skim through UX Laws

### ISSUE THREAD

**Issue by Saishreekouda** [opencodeiiita/DonateASmile#33]
**OPEN TO ALL. NO NEED TO CLAIM. NO SUBMISSION WILL BE ACCEPTED AFTER 24TH DEC 2PM.**

Are you enjoying your work as a UX designer, probably first time in your life thinking about things from users' point of view. 

Visit this site [https://lawsofux.com/](https://lawsofux.com/) and try to skim through some of the laws of the UX, no need to read all of them only reading few will be enough for this task.

Your task is to identify 3 such UX laws that have come into play on this [https://www.mural.co/](https://www.mural.co/) website. Elaborate on how the laws have been applied or are coming into play. Present your thoughts in any format that seems appropriate to you. YOU MUST include screenshots of the section where you feel the laws have been used and explain how the laws have been applied. Go be lawyers of UX!😎

## Submission Guideline:

Submit your ideas in google doc and provide the link in a txt file and place it in the ‘UX Laws’ folder.

## Minimum Design Criteria (MDC)

Pointing out 3 laws of UX that have been applied on [https://www.mural.co/](https://www.mural.co/) with screenshots of the section being referred to along with brief explanation of how the law has been applied in that section.

**Comment by nityagupta6** [comment]
Nicee try!...but the laws used in 2nd and 3rd example are not correct pls go through all the laws and recheck as to which law has been used
