### ISSUE TITLE
Short UX Task

### ISSUE THREAD

**Issue by Saishreekouda** [opencodeiiita/DonateASmile#4]
**OPEN TO ALL No need to claim this issue NO SUBMISSION WILL BE ACCEPTED AFTER 19th December 06:00 PM**

While you are working on the best user flow for the DonateASmile app, here is another short task to test your thinking 🤔 as User Experience Designer!.
The task is brief and doesn't take much time, but what it actually requires is a strong eye for seeing things from the perspective of the user.

Everything in this world happens for a reason, and the **Spotify home page** 🎵 also appears a certain way for a variety of reasons to provide users with a better experience and ease of use.
The only thing you need to do is write down your ideas on why the Spotify home page is designed the way it is, why the playlists and songs are organised the way they are, and why everything is situated in the locations that it is 😂.

If you are confident enough you can even suggest changes in the layout or any other aspect of the homescreen which might lead to better user experience than it currently offers. 

Happy UXing contributors!

## Submission Guideline:

- Write your views on google doc.
- Provide the link of google docs in a .txt file. Make sure that the link is accessible (and not private).
- Submit your txt files in the 'Short UX Task' folder only.

## Minimum Design Criteria (MDC)

Atleast suggest two features of the homescreen and how they contribute to good user experience and how the experience would have been worse if these features would have been implemented differently. You can also suggest two changes if that is what you prefer.

  

> Features need not be very significant functions of the homescreen, they can be as simple as why the first thing on the screen is ‘Good evening’ or ‘Good morning’ or why the most listened albums are on the top or **anything which is similarly simple.**
>

**Comment by vedant-z** [comment]
@Saishreekouda This repo is GIRLS ONLY or anyone can make a PR?

**Comment by Saishreekouda** [comment]
> @Saishreekouda This repo is GIRLS ONLY or anyone can make a PR?

Anyone can make a pr
